### ISSUE TITLE
GPG Key Error on step 26 of build

### ISSUE THREAD

**Issue by jonathanabennett** [firefly2442/aurora4x-docker#10]
When running the build according to the instructions in the readme, I get the following error:
```
W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B
E: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is not signed.
```
This is during step 26, which is:
```
Step 26/34 : RUN sudo apt update &&     sudo apt install -y --no-install-recommends gnupg ca-certificates &&     sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&     echo "deb https://download.mono-project.com/repo/ubuntu preview-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-preview.list &&     sudo apt update &&     sudo apt install -y --no-install-recommends mono-complete fonts-cantarell &&     rm -rf /var/lib/apt/lists/*
 ---> Running in f7d80d5746ee
```

Adding the following line before step 26 solves the problem:
`wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -`

At this point, I am also working on getting it to apply patches 2.1.0 and 2.1.1 during the docker build as well. I will go ahead and for the repository so I can submit a pull request with these changes.

**Comment by firefly2442** [comment]
Yep, I think I got those addressed.  Give it a try and let me know if you still have issues building it.  Thanks

**Comment by jonathanabennett** [comment]
I don't think the changes have been pushed to this repo yet.

**Comment by jonathanabennett** [comment]
Whoops! Sorry, I missed the commit before. I'm trying it now.

**Comment by jonathanabennett** [comment]
Resolved on Linux. It doesn't work on Apple M1 chips, but this is a problem with Apple and Mono which is well beyond the scope of this project. Thank you!
