### ISSUE TITLE
Tweek to Aurora.db Mount Location

### ISSUE THREAD

**Issue by ConnorBrockbank** [firefly2442/aurora4x-docker#16]
Hi,

I'm not sure if this is an issue for anyone else but I had to change the location of the AuroraDB.db in the image from /root/AuroraDB.db to /config/AuroraDB.db to allow it to save back to my desktop. This is just based on where things seem to be located in the container's filesystem.

I also noticed Podman would complain when using --name=aurora4x-docker.
`Error: error creating container storage: the container name "aurora4x-docker" is already in use by "0bbb1442bde211662b1c8ff7b117c1d5c1c030613417045855373e0e0ed059d8". You have to remove that container to be able to reuse that name.: that name is already in use`
I'm sure this is probably just an issue with Podman not being Docker so no worries here haha.

The command I run now after sudo podman pull <image_location>:
`sudo podman run -p 6080:3000 -v /dev/shm:/dev/shm -v /<path_to_auroradb>/AuroraDB.db:/config/AuroraDB.db aurora4x-docker`

I also noticed that the default user doesn't have access to write to some locations so it can save or start a new game. I ended up running sudo /config/Aurora.sh manually rather than the desktop shortcut to work around this.

Regardless, I'd like to say great work and thanks so much for doing this!

Also, if you don't want to update your image every time a minor update comes out you could include instructions on how to also mount the user's aurora.exe.

-Connor

**Comment by ConnorBrockbank** [comment]
I was so bold to create a pull request.

**Comment by ConnorBrockbank** [comment]
Closed by mistake.

**Comment by firefly2442** [comment]
Thank you
