### ISSUE TITLE
Mono submodules not downloading

### ISSUE THREAD

**Issue by jonathanabennett** [firefly2442/aurora4x-docker#9]
When running the build step, I got a connection error on each of the submodules for Mono. I followed the instructions in this SO answer:
https://stackoverflow.com/questions/12535637/updating-git-submodule-fails
And added this line of code to the Dockerfile before the line cloning Mono:
`RUN git config --global url."http://github".insteadOf git://github`
And that has fixed the problem.

**Comment by firefly2442** [comment]
Thanks very much, got this merged in as well as updates for the latest version of Aurora.
